# Uncomment the next line to define a global platform for your project
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'verdgas' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  # Pods for verdgas
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'verdgasTests' do
    inherit! :complete
    # Pods for testing
  end

  pod 'react-native-maps', path: rn_maps_path
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end



  # maps
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-google-maps'
        target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
        end
      end
      if target.name == "React"
        target.remove_from_project
      end
    end
  end

